"""ACN-Data session ingestion scaffold for Grid-FedGAT-Safe validation.

This script prepares the remaining public-session experiment. It can read either
an ACN-Data API token from ``ACN_API_TOKEN`` or a local JSON export specified by
``ACN_DATA_JSON``. If neither is available, it writes a blocked summary instead
of fabricating public-session results.

Outputs:
  results/acn_data_validation_summary.md
  results/acn_data_sessions.csv, when sessions are available
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Iterable, List

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]
RESULTS_DIR = PROJECT_ROOT / "results"
SITES = ("caltech", "jpl", "office001")
MAX_SESSIONS = 5000


def normalize_session(doc: dict, fallback_site: str) -> dict | None:
    connection = doc.get("connectionTime")
    disconnect = doc.get("disconnectTime") or doc.get("doneChargingTime")
    energy = doc.get("kWhDelivered") or doc.get("energyDelivered")
    station = doc.get("spaceID") or doc.get("stationID") or doc.get("EVSEID")
    if connection is None or disconnect is None or energy is None:
        return None
    try:
        energy = float(energy)
    except (TypeError, ValueError):
        return None
    if energy <= 0:
        return None
    return {
        "site": doc.get("site") or fallback_site,
        "session_id": doc.get("sessionID") or doc.get("_id") or "",
        "station_id": str(station or "unknown"),
        "connection_time": str(connection),
        "disconnect_time": str(disconnect),
        "energy_kwh": energy,
        "timezone": doc.get("timezone", ""),
    }


def load_export(path: Path) -> pd.DataFrame:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(payload, dict) and "_items" in payload:
        docs = payload["_items"]
    elif isinstance(payload, dict) and "sessions" in payload:
        docs = payload["sessions"]
    elif isinstance(payload, list):
        docs = payload
    else:
        raise ValueError("Unsupported ACN JSON export shape")
    rows = [normalize_session(doc, "local_export") for doc in docs]
    rows = [row for row in rows if row is not None]
    return pd.DataFrame(rows)


def fetch_api(token: str) -> pd.DataFrame:
    from acnportal.acndata import DataClient

    client = DataClient(token)
    rows: List[dict] = []
    end = datetime.now(timezone.utc)
    start = end - timedelta(days=365)
    for site in SITES:
        for doc in client.get_sessions_by_time(site, start=start, end=end, min_energy=1.0):
            row = normalize_session(doc, site)
            if row is not None:
                rows.append(row)
            if len(rows) >= MAX_SESSIONS:
                return pd.DataFrame(rows)
    return pd.DataFrame(rows)


def write_summary(status: str, detail: str, rows: int = 0) -> None:
    RESULTS_DIR.mkdir(exist_ok=True)
    summary = f"""# ACN-Data Validation Summary

Generated by `simulations/acn_data_validation.py`.

Status: **{status}**

{detail}

Rows normalized: `{rows}`.

## Next Step

Provide either:

- `ACN_API_TOKEN`, a registered ACN-Data API token, or
- `ACN_DATA_JSON`, a path to a local ACN-Data JSON export containing session records.

When session records are available, this script writes
`results/acn_data_sessions.csv` for the final public-session replay.
"""
    (RESULTS_DIR / "acn_data_validation_summary.md").write_text(summary, encoding="utf-8")


def main() -> None:
    RESULTS_DIR.mkdir(exist_ok=True)
    export_path = os.environ.get("ACN_DATA_JSON")
    token = os.environ.get("ACN_API_TOKEN")
    try:
        if export_path:
            df = load_export(Path(export_path))
            source = f"Loaded local ACN-Data JSON export `{export_path}`."
        elif token:
            df = fetch_api(token)
            source = "Fetched ACN-Data sessions through the registered API token."
        else:
            write_summary(
                "blocked",
                "No `ACN_API_TOKEN` or `ACN_DATA_JSON` was provided. Direct API checks without credentials return HTTP 401: proper credentials are required.",
            )
            return
    except Exception as exc:  # Keep the blocker visible in a result artifact.
        write_summary("blocked", f"ACN-Data ingestion failed: `{type(exc).__name__}: {exc}`.")
        raise

    if df.empty:
        write_summary("blocked", f"{source} No usable charging sessions were found.", rows=0)
        return

    df.to_csv(RESULTS_DIR / "acn_data_sessions.csv", index=False)
    write_summary(
        "ready",
        f"{source} Normalized public charging-session records are available for replay.",
        rows=len(df),
    )


if __name__ == "__main__":
    main()
